# Generated by Django 2.2.3 on 2019-10-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='time',
            field=models.TimeField(default=False),
        ),
    ]
