# Generated by Django 2.2.3 on 2019-10-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_loginmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='time',
            field=models.TimeField(),
        ),
    ]
