# Generated by Django 2.2.3 on 2019-10-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191019_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='time',
            field=models.TimeField(default=False),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='username',
            field=models.IntegerField(unique=True),
        ),
    ]
