# Generated by Django 2.2.3 on 2019-10-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191019_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('idno', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('desig', models.CharField(max_length=30)),
                ('sala', models.DecimalField(decimal_places=2, max_digits=10)),
                ('username', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginModel',
        ),
    ]
